"""add language

Revision ID: a10dfa978f7d
Revises: edecba1a5afe
Create Date: 2021-11-20 14:43:32.229635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a10dfa978f7d'
down_revision = 'edecba1a5afe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word', sa.Column('language', sa.Enum('german', 'english', name='language'), nullable=True))
    op.execute("update word set language = 'german'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('word', 'language')
    # ### end Alembic commands ###
