"""create word table

Revision ID: edecba1a5afe
Revises: 
Create Date: 2021-11-20 12:33:21.756932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edecba1a5afe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('verb', 'noun', 'adjective', 'pronoun', 'numeral', 'adverb', 'preposition', 'article', 'participle', name='category'), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('global_rank', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word')
    # ### end Alembic commands ###
